#!/bin/bash

repo_encoded="aHR0cHM6Ly9naXRodWIuY29tL0FzaHFhbHNt dC9Tb3VyY2UxLmdpdA=="
branch="main"  

_run_git_clone () {
    echo "⌭ جاري تحميل سورس يـــمنثون ⌭"
    repo_url=$(echo "$repo_encoded" | base64 -d)
    git clone -b "$branch" "$repo_url" source_temp
    cd source_temp
}

_install_requirements () {
    echo "⌭ تثبيت مكاتب يمنثون ⌭"
    pip install -r requirements.txt
}

_start_project () {
    echo "⌭ بدء تشغيل يمنثون ⌭"
    python3 server.py & python3 -m yamenthon
}

_run_git_clone
_install_requirements
_start_project